#开发环境
breakpoint:
  upload:
    dir: D:/test/uploads/
    #1024*1024=1 048 576,5M=5 242 880
    chunkSize: 5 242 880

spring:
  redis:
    # 地址
    host: 10.16.78.225
    # 端口，默认为6379
    port: 6380
    # 数据库索引
    database: 0
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  http:
    multipart:
      max-file-size: 5MB
      max-request-size: 100MB
