server:
  port: 8000

spring:
  profiles:
    active:
      - dev
appsetting:
  logMode: k8s

eventhub:
  setting:
    enable: true

logback:
  home: /test/logback

management:
  endpoints:
    web:
      base-path: /actuator
#  endpoint:
#    health:
#      roles: admin
#    info:
#      roles: admin
#    configprops:
#      roles: admin
#    env:
#      roles: aadmin
#    logfile:
#      roles: admin
#    threaddump:
#      roles: admin
#    metrics:
#      roles: admin
