server:
  port: 8080
database:
  #url: jdbc:mysql://172.24.77.44:3306/deal?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
  /url: jdbc:mysql://47.98.128.88:3306/autoSubmit?useUnicode=true&characterEncoding=utf-8&useSSL=false
  username: root
  password: kindy0916
spring:
  datasource:
    url: ${database.url}
    username: ${database.username}
    password: ${database.password}
    #使用阿里巴巴Druid数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
